AlignParameters:
  EnforcedStyle: with_fixed_indentation
AllCops:
  Exclude:
  - tmp/*
HandleExceptions:
  Enabled: false
NonNilCheck:
  Enabled: false
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
TrivialAccessors:
  ExactNameMatch: true
