AllCops:
  Excludes:
    - tmp/*

AlignParameters:
  Enabled: false

ClassLength:
  Max: 110

HandleExceptions:
  Enabled: false

PredicateName:
  Enabled: false

TrivialAccessors:
  ExactNameMatch: true
