AllCops:
  Exclude:
  - example/db/schema.rb
  - tmp/**/*
  - vendor/**/*
Documentation:
  Exclude:
  - spec/**/*
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/ClassLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/FileName:
  Exclude:
  - gemfiles/*
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
