AlignParameters:
  EnforcedStyle: with_fixed_indentation
AllCops:
  Exclude:
  - example/db/schema.rb
  - tmp/**/*
  - vendor/**/*
HandleExceptions:
  Enabled: false
MultilineOperationIndentation:
  Enabled: false
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
TrivialAccessors:
  ExactNameMatch: true
