AlignParameters:
  EnforcedStyle: with_fixed_indentation
AllCops:
  Exclude:
  - example/db/schema.rb
  - tmp/**/*
  - vendor/**/*
ClassLength:
  Max: 150
Documentation:
  Exclude:
  - spec/**/*
FileName:
  Exclude:
  - gemfiles/*
MultilineMethodCallIndentation:
  EnforcedStyle: indented
MultilineOperationIndentation:
  Enabled: false
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': '[]'
    '%i': '[]'
    '%w': '[]'
