AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - example/db/schema.rb
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
Naming/FileName:
  Exclude:
    - gemfiles/*
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*.gemspec'
    - Rakefile
    - Gemfile
    - gemfiles/*
    - spec/**/*
    - benchmarks/*.rb
Style/OpenStructUse:
  Enabled: false
