AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - example/db/schema.rb
  - tmp/**/*
  - vendor/**/*
ClassLength:
  Max: 120
Documentation:
  Exclude:
  - spec/**/*
FileName:
  Exclude:
  - gemfiles/*
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*.gemspec'
    - Rakefile
    - Gemfile
    - gemfiles/*
    - spec/**/*
    - benchmarks/*.rb
