before_install: gem update bundler
env: RAKE_TASK=spec
language: ruby
matrix:
  include:
  - env: RAKE_TASK='spec rubocop'
    rvm: 2.1
  - gemfile: gemfiles/activemodel3.rb
    rvm: 2.1
notifications:
  email: false
  hipchat:
  - secure: 'UXiSnDlm3hzEIzImCMtHriu1w9T8ZQi27WR0DxiA18OZ1swyHcRaFvOR/WGn

      Q3JHLQ42o2utpc4IiMiKmD/2GIu5nququXqRYHF65Urrqrf1ymcGWlas5G6C

      ivR5nEELqEsDgDZAcKGJtRgp70d6Geg5iFUfV9aP1ySy2U0AXBM='
rvm:
- 2.1
- 2.0
- 1.9
- jruby
- rbx-2
script: bundle exec rake $RAKE_TASK
