sudo: false
before_install: gem update bundler
language: ruby
matrix:
  include:
  # This tests the "default" configuration.
  # Latest MRI, default Gemfile, default Rake task
  - rvm: 2.3.1

  # These test specific versions of ActiveModel that we support.
  # Latest MRI, ActiveModel 4.2, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.2.rb
    rvm: 2.3.1
  # Latest MRI, ActiveModel 4.1, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.1.rb
    rvm: 2.3.1
  # Latest MRI, ActiveModel 4.0, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.0.rb
    rvm: 2.3.1

  # These test specific versions of MRI that we support.
  # MRI 2.2, ActiveModel 4.2, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.2.rb
    rvm: 2.2.5
  # MRI 2.1, ActiveModel 4.2, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.2.rb
    rvm: 2.1.9
  # MRI 2.0, ActiveModel 4.2, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.2.rb
    rvm: 2.0.0-p648

  # These test other Ruby implementations that we support.
  # JRuby 9, ActiveModel 4.2, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.2.rb
    rvm: jruby-9.0.5.0
  # Rubinius 3, ActiveModel 4.2, RSpec only
  - env: RAKE_TASK=spec
    gemfile: gemfiles/activemodel-4.2.rb
    rvm: rbx-3
notifications:
  email: false
  hipchat:
  - secure: 'UXiSnDlm3hzEIzImCMtHriu1w9T8ZQi27WR0DxiA18OZ1swyHcRaFvOR/WGn

      Q3JHLQ42o2utpc4IiMiKmD/2GIu5nququXqRYHF65Urrqrf1ymcGWlas5G6C

      ivR5nEELqEsDgDZAcKGJtRgp70d6Geg5iFUfV9aP1ySy2U0AXBM='
script: bundle exec rake $RAKE_TASK
