require 'active_model'

require 'active_interaction/version'
require 'active_interaction/errors'
require 'active_interaction/attr'
require 'active_interaction/attr_block'
require 'active_interaction/array_attr'
require 'active_interaction/boolean_attr'
require 'active_interaction/float_attr'
require 'active_interaction/hash_attr'
require 'active_interaction/integer_attr'
require 'active_interaction/model_attr'
require 'active_interaction/string_attr'
require 'active_interaction/base'
